version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    network_mode: host
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: users
  short-link-app:
    build:
      context: .
      args:
        NODE_VERSION: "16"
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users